### ISSUE TITLE
is it possible to have 2 images by slide with no margin between them ?

### ISSUE THREAD

**Issue by jhaya93** [antoniandre/vueper-slides#117]
Hello...Vueperslide is a really great slider, im trying to get landscape and portrait images in the same `<vueper-slide >` my problem is i cant find a way to get the 2 portrait images with no gaps between. 

```
<vueper-slides  class="no-shadow"  :class="talent_portfolio.name" arrows-outside center  :bullets="false" :gap="0"  :draggingDistance="10"   :transitionSpeed="0" :visibleSlides="2" 
slide-multiple   :slideImageInside="true" >
```
Im trying to get this result [
![vueper](https://user-images.githubusercontent.com/74786858/100593628-e3cbe200-32f8-11eb-84f5-edf7ad5eef9f.jpg)
](url)

If someone can help me get the 2 portrait images with no gap ?
Thank you for your help

**Comment by antoniandre** [comment]
Hi @jhaya93, 
Sorry for the (too?) late reply.
Yes this is possible to do, I created a Codepen demo for you: https://codepen.io/antoniandre/pen/qBRgPPr

Just to explain what I did: 
- you want custom slide content so you can have 2 images in 1 slide then 1 image in the second slide
- don't need the image-inside prop if you're going to do custom slides 
- setting the gap to `0` is like not setting it, so don't need this prop
- you need the visible-slides prop to be set to 2 like you did
- in my example I set every odd number slides to show 2 images (with a modulo), but you probably want to have a different condition
- in the slide content, you should use a div with a background image rather than an img tag, so that you can force a ratio and crop the image to aways fit and cover the space
- the CSS `background-size: cover` & `background-position: center` are important to display the image correctly.
- the CSS `padding-bottom: 70%;` (with no height) on images is a trick to keep the same ratio when you resize the browser

Also just a tip, since HTML is case-insensitive, you should always convert your props to kebab-case, e.g. `visibleSlides` => `visible-slides`.

Hope it can still help, even late! Cheers :)
