### ISSUE TITLE
Vite support (Webpack doesn't bundle to ESM)

### ISSUE THREAD

**Issue by inspiredlabs** [antoniandre/vueper-slides#120]
Hi Antoni,
  Vueperslides looks excellent – I'd really like to use Vueperslides for my artwork. 

For simplicity, I'm using [this method of installation](https://www.youtube.com/watch?v=A_COUB-SLsc), which throws 45 errors:

![Vite throws 45 errors when used with Vueperslides](https://inspiredlabs.co.uk/vite/screenshot.jpg)

These include multiple occurrences of: 
`resolveComponent can only be used in render() or setup().`
`Invalid VNode type: Symbol(Comment) (symbol) at <VueperSlides>`
`Invalid VNode type: Symbol(Fragment) (symbol) at <VueperSlides>`
`Missing ref owner context. ref cannot be used on hoisted vnodes. A vnode with ref must be created inside the render function. at <VueperSlides>`

~~Can you provide any guidance for handling the next-steps?~~ The other method for installing [Vite](https://github.com/vitejs/vite#getting-started), doesn't cause issue. 

Also, would it be worth having a SFC demo on [Codepen](https://codepen.io/yyx990803/pen/OJNoaZL) for Vue 3?

**Comment by antoniandre** [comment]
Hi @inspiredlabs,
Sorry I've been busy relocating for the past few weeks.

Regarding the Codepen demo of Vueperslides on Vue 3, it's already available here: https://codepen.io/antoniandre/pen/xxOgGEK, makes me notice there is no link in the documentation, will add it soon.

Regarding Vite & Rollup, as you say Webpack is not yet doing ESM modules.
I haven't personally used Vite so I only know you have to bundle Vueperslides yourself to be able to use in Vite.
If you made it work with this, then all good! Otherwise let me know where you're at.

> ~Can you provide any guidance for handling the next-steps?~ The other method for installing [Vite](https://github.com/vitejs/vite#getting-started), doesn't cause issue.

**Comment by CalebKester** [comment]
I'm using this in Vite with no issues. I suspect the issue was the Vue3 support.

**Comment by antoniandre** [comment]
Vueper Slides now have an ESM bundle.
Works with vite, works with Vue 3.
