### ISSUE TITLE
lazy-load-on-drag issue

### ISSUE THREAD

**Issue by musashiM82** [antoniandre/vueper-slides#137]
hi
there is an issue when lazy-load-on-drag is used, it loads same image 2 times.
issue is present also on your site

![ezgif-2-13c643bd1558](https://user-images.githubusercontent.com/41707194/112665224-1d51cb80-8e5b-11eb-9b63-14370fa37b30.gif)

**Comment by saschamander** [comment]
I'm currently facing the same problem. Are there any updates on this?

**Comment by antoniandre** [comment]
Hi @musashiM82,
Sorry for late reply.
This is normal, it is only happening because you disable the cache in the dev tools.
Try again with cache.

Just to explain, the image source is used twice because it's first pre-loaded (so we can display a spinner until fully loaded), then loaded in an <img> tag or as a background (depends how you configure Vueper Slides).

this is completely normal behavior.
cheers
