### ISSUE TITLE
disableArrowsOnEdges blocks the keyboard arrows until you change to the second slide

### ISSUE THREAD

**Issue by Juandresyn** [antoniandre/vueper-slides#16]
I just find out that `disableArrowsOnEdges` blocks the keyboard arrows until you changes to the next slide.

Reproduce:

- Load the page where your slider is.
- Try to move using the keyboard arrows
- Move manually or using the carousel controllers (bullets, arrows) to the next slide
- Hit again the keyboard arrows

**Comment by antoniandre** [comment]
@Juandresyn I can't seem to reproduce or I might be misunderstanding.

Do you also see the issue on the example https://antoniandre.github.io/vueper-slides/#ex--add-remove-slides--disable which uses the `disableArrowsOnEdges` config?
You can add slides with the button to have more slides to test keyboard arrows.

_____

Or are you trying to move with keyboard arrows beyond the slideshow end?
If so, this is the expected behavior as `disableArrowsOnEdges` also disable the `infinite` mode, so it would be inconsistent to allow keyboard arrow to go back to beginning after last slide.

**Comment by antoniandre** [comment]
Closed for inactivity.
