### ISSUE TITLE
Slider buttons are not ADA compliant

### ISSUE THREAD

**Issue by davidmgrana** [antoniandre/vueper-slides#184]
Hi there,

Looks like arrow buttons are missing tabindex attribute so they are not focusable.

This is hurting our accessibility scores, can you please make this change or add an option when initializing the slider?

**Comment by antoniandre** [comment]
Hi @davidmgrana,
Could you share the accessibility report that says buttons need a tabindex?

Because usually a tabindex is placed on elements that are not naturally tabable like div, span, but not on a button.
And in Vueper Slides the arrows are native buttons: they are naturally focusable as per screen recording

https://user-images.githubusercontent.com/22971289/183248164-96c27ed5-6a9a-46ff-befe-99e05719fec0.mov

**Comment by davidmgrana** [comment]
Hello there!

Yes i think you are right, although it seems to be expected to be operable with the keyboard.

Let me just forward their comments:

**Acceptance Criteria**
1. Go to the URL.
2. Navigate through the page using the keyboard until you reach the "Next" and "Previous" button.
3. Notice that focus does not reach the "Next" and "Previous" button.

**Expected Result**
The "Next" and "Previous" button is operable and focusable by the keyboard.

**Recommendation**
The button should be focusable and operable by the keyboard.
Use the proper <button> tag.

Alternatively, use a tabindex="0" attribute to make the item focusable.
Add a role="button" and make sure the element can be triggered when using the SPACE bar or ENTER key.

Only use ARIA if necessary. Otherwise use HTML controls.

**Resources**
The ARIA button role:
[ARIA: button role - Accessibility | MDN](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/button_role)

**Comment by davidmgrana** [comment]
Hello there!

I think you are right, problem seems to be that there's no styling or outline on the buttons so you don't know when they are focused. I can take care of this on my end, thank you
