### ISSUE TITLE
Parallax background with stationary title/content

### ISSUE THREAD

**Issue by dapperdanman1400** [antoniandre/vueper-slides#25]
I'd like a possibility to have stationary titles/content with a parallax background. Right now, I can kind of simulate this with `slideContentOutside` and then absolutely position it over the background, but it's a rather convoluted solution to this issue.

**Comment by antoniandre** [comment]
Hi @dapperdanman1400, thanks for your feedback.

I think what you did is the way to go.
Unfortunately, moving the parallax calculation into each slide instead of outer container like now (so the slide title and content don't move) would be way more expensive as it would have to modify the CSS style transformation in each slide instead of once at every movement of scroll.
It would certainly degrade the user experience.
