### ISSUE TITLE
Long drag only advances one slide

### ISSUE THREAD

**Issue by 719media** [antoniandre/vueper-slides#33]
I'm checking out your library as a longtime user of https://idangero.us/swiper/ who also uses vue.

Your library is awesome! There were a few things I thought worth mentioning in case they were helpful ideas for you.

1) When doing a long drag, the slide would only advance by one. For example, on the `6 visible slides, sliding 1 by 1, full-width, no arrows, dragging distance of 70px` multiple slides example, if you slide over an entire "screen" worth, you still only advance to the 2nd slide. This just seems unintuitive to me, and I would expect the active slide to be closer to where the drag terminated.

2) Having the slide automatically travel to the touch point was definitely new (e.g. when putting finger/clicking on the slide, it moves to that point as if you had started the drag from the edge of the screen already). It's a cool effect, not sure how expected it is for an everyday average web user. I did see that this effect was disabled when using the dragging distance property. I suppose I was just surprised that there wasn't documentation/information about this feature, and under what circumstances it is enabled/disabled.
(Basically I'm referring to https://github.com/antoniandre/vueper-slides/blob/master/src/components/vueperslides/vueperslides.vue#L462-L464)

3) Disabling Y scroll while X scroll active. I think it's more pleasing to not allow body Y scroll WHILE X scroll is actively scrolling.

Thank you for your time.

**Comment by antoniandre** [comment]
Hi @719media,
Thank you for your feedback and sorry for the delay, I am very busy atm.
I understand well what you say. 

1. For the long drag, limited to one slide increment at a time, this is purposely done so there is no possible bug when you go fast and should cross the slide clone and start over from beginning.
This is most important for the 3D rotation example, as we overlap faces with nearest slides (imagine a cube of 4 side faces but 9 slides...).
I understand it can be frustrating but I can't provide other option when there are slide clones (infinite mode).
2. for the effect of the slide going to your touch point from the closest end, this is a visual feedback to show you what happened when you press and hold, then by default, you just have to cross the middle of the slideshow. This is the default behavior that I wanted for Vueperslides. For those who don't like this behavior, I implemented the more common dragging distance which replaces the other behavior and the slide stays at its place when click and hold. The first option is maybe less intuitive the first time you use it but once you've seen it in action you understand how to do. I guess. haha
3. This should probably be an option, some may want to keep the vertical scroll so that on mobile when you touchmove from down to top intending to scroll down on a big header slideshow but kind of go diagonal, it will still go down as well as move the slide a little and give you an indication that this slideshow is also scrollable. So I will add this option in a future release to allow user to choose.

Thanks for your ideas and feedback!

**Comment by antoniandre** [comment]
Hi @719media, I have added the option to prevent y-scrolling while dragging in version 1.20.0.
Please refer to this example: https://antoniandre.github.io/vueper-slides/#ex--dragging-distance
(it's only noticeable on touch device).
