### ISSUE TITLE
Images as slide content

### ISSUE THREAD

**Issue by Byloor** [antoniandre/vueper-slides#54]
I am not sure, if the following is an issue or intended behavior.
Is it not possible to have images as slide content. (Not as background image.). 
The problem with background image is the complete image cannot not shown sometimes.

**Comment by antoniandre** [comment]
Hi @Byloor,
This is by design. 

- If all your images are cut, it probably means you don't give the good image ratio through `slide-ratio`. 
- If only some of your slides images are cut, this is why Vueperslides does not have an image tag, because we want the slideshow to always have the same height - which you can force through `fixed-height`.

I hope it's clear, here is another set of examples dedicated to illustrate `slide-ratio`: https://codepen.io/antoniandre/pen/KBXWPP

Let me know if you have more questions.
Cheers.

**Comment by afaq-karim** [comment]
We can't use img tag as i want my images to be SEO using alt text
