### ISSUE TITLE
Gradient left/right slides

### ISSUE THREAD

**Issue by StanZhuravlev** [antoniandre/vueper-slides#62]
Hi!

Can I make a gradient to full opacity slides from left & right sides? May be anybody has this experience?

**Comment by antoniandre** [comment]
Hi @StanZhuravlev,

As expected there is no magic to fade your slide images outside of the image itself, that means you would have to re-edit the images and put the opacity gradient directly in it.

**But good news if your background has a single color!** 
Here is a demo of how you can achieve the same outcome with a little trick:
https://codepen.io/antoniandre/pen/rNaNaZP?editors=0100

So the trick is to add a layer on top of Vueper Slides that has the same plain color as your background, since with CSS we can easily do a gradient from a plain color to transparent.

Let me know if that's what you are looking for.

**Comment by StanZhuravlev** [comment]
Wow! I have a white background :) And you solution on codepen is very good for me. Thank you!
