### ISSUE TITLE
Margin between items

### ISSUE THREAD

**Issue by JorgeRaboso** [antoniandre/vueper-slides#66]
Hello,

Is it not possible to add a margin between elements?
With a parameter like: ": margin: 20"

Thanks

**Comment by antoniandre** [comment]
Hi @JorgeRaboso, 
That's a useful feature indeed, I will work on it soon, will let you know when ready.

**Comment by antoniandre** [comment]
Hi @JorgeRaboso,
The feature is now released in version 2.3.0.
The `gap` option accept a number in percentage.

https://antoniandre.github.io/vueper-slides/#ex--show-multiple-slides-and-gap

hope it helps.

**Comment by JorgeRaboso** [comment]
Thank you. Very useful. I will implement it in my project.

regards

**Comment by JorgeRaboso** [comment]
Hi @antoniandre ,

Would it be possible to add the option to put pixels?
In percentages you cannot control the design so much.

Thanks

**Comment by antoniandre** [comment]
Hi @JorgeRaboso, 
At the moment this would not be possible as all Vueper Slides is based on percentage calculations for more performance.

Also, even if mixing pixels and percentage is possible in CSS 3 (via CSS the `calc()` property) and would not require too much work to allow gap in pixels, transitions involving `calc()` is not supported in IE 11. So that's won't be a quick hack.

I keep this request in my to do list and will see if I can have an option to switch the whole slideshow to pixel base.
