### ISSUE TITLE
Turn off active slide to center on Sync 2 instances

### ISSUE THREAD

**Issue by zhuxiaoyu88** [antoniandre/vueper-slides#74]
Hi, I faced this issue when I created vueper sync 2 instances. The second slider not stay on the left when it slides after third slide. Maybe this happened because the second slider has visible slides more than the available data. How could fix this ? Thank you
[ here the result]
![gerak2](https://user-images.githubusercontent.com/46235179/73904386-da3f3c80-48d6-11ea-8865-3db9bdee7c66.PNG)
and my code
`
<vueper-slides :touchable="false" fade autoplay :bullets="false" ref="vueperslides1" @slide="$refs.vueperslides2 && $refs.vueperslides2.goToSlide($event.currentSlide.index, { emit: false })" fixed-height="350px">
                <vueper-slide v-for="(slide, i) in slider.data" :key="i" :style="slider.data.length === 0 ? { 'background-color' : '#f2f2f2' } : { 'background-image' : 'url(' + slide.image + ')' }" />
              </vueper-slides>
              <hr>
              <vueper-slides ref="vueperslides2"  @slide="$refs.vueperslides1 && $refs.vueperslides1.goToSlide($event.currentSlide.index, { emit: false })" :visible-slides="8" fixed-height="75px" :bullets="false" :gap="2.5" :arrows-outside="false" :slide-ratio="1 / 4">
                <vueper-slide v-for="(slide, i) in slider.data" :key="i" :style="slider.data.length === 0 ? { 'background-color' : '#f2f2f2' } : { 'background-image' : 'url(' + slide.image + ')' }" @click.native="$refs.vueperslides2 && $refs.vueperslides2.goToSlide(i - 1)" />
              </vueper-slides>
`

**Comment by antoniandre** [comment]
Hi @zhuxiaoyu88,

Indeed the problem comes mainly because you had `:visible-slides="8"` which is more than the number of slides you have.
I have corrected a few things from your sample and created a demo for you: https://codepen.io/antoniandre/pen/ZEGEydP

Also here are a few other tips to make it work perfectly and help you understand:
- If you want the thumbnails to be smaller, you can put a max-width on the Vueper Slides instance
- You don't need a `slide-ratio` if you have a `fixed-height`
-  You don't need to check `slider.data.length === 0` inside the v-for if the v-for is `(slide, i) in slider.data`
- Instead of setting the image background in a style yourself, you should let Vueper Slides do it passing only the url in `:image=""` 
- You should use the class `no-shadow` on the thumbnails bar if you keep the gaps
- You should set `:touchable` to false (or set a `dragging-distance`) on the thumbnails bar so that it does not "jump" on click

Hope it helps!

**Comment by zhuxiaoyu88** [comment]
Hi Antoni, thank you for your fast response. But, I have to set the visible
slide to 8. Is is possible to achieve that? Thank you

**Comment by zhuxiaoyu88** [comment]
![like-this](https://user-images.githubusercontent.com/46235179/73995665-43d15080-4994-11ea-9f58-fd770ff38a46.PNG)
![this-2](https://user-images.githubusercontent.com/46235179/73995673-48960480-4994-11ea-94f2-0d2b5398723c.PNG)

Maybe these pics can explain clearer
[pic 1] eventhough I'm in last slide and the visible slide is bigger than the available data, the sliders always stay on the left. This sliders based on jQuery

Is it possible to achieve that ? (maybe with css)

**Comment by antoniandre** [comment]
Hi @zhuxiaoyu88,

This is definitely possible with a bit of CSS and logic, here is a demo of what you want:
https://codepen.io/antoniandre/pen/BaNNmxj

As you always want 8 thumbnails placeholders, whatever the number of pics you have, you must set the visible slides to `Math.min(8, slides.length)` so it will stay fixed when you have less pics and it will scroll when there are more than 8 pics.
You can try to comment a few slides in the javascript pane to see how it behaves with less than 8 pics.

With this code, the full slideshow will remain fully responsive and will adapt to the container width (thanks to percentage calculations and not pixels).

Hope it solves your problem.

**Comment by zhuxiaoyu88** [comment]
Wow, it works well. Thank you !
